---
- name: "Adding Postgresql repository signing key"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: "Adding Postgresql repository"
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present
    filename: pgdg
  register: psql_repo

- name: "update apt cache"
  when: psql_repo.changed == true
  apt:
    update_cache: yes

- name: "Installing postgresql-11"
  apt:
    name:
      - openjdk-11-jdk
      - postgresql-11
      - php7.2-pgsql

- name: "Creating conf files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "postgres"
    group: "postgres"
  with_items:
    - {src: 'pg_hba.j2', dest: '/etc/postgresql/11/main/pg_hba.conf'}
    - {src: 'postgresql.j2', dest: '/etc/postgresql/11/main/postgresql.conf'}
